config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  root "feed#show"

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :listings, except: :index do
    scope module: :listings do
      post :draft, to: "drafts#create", on: :collection
      patch :draft, to: "drafts#update"

      resource :contact, only: [ :show ], controller: "contact"
    end

    resource :saved_listings, only: [ :create, :destroy ], path: "save"
  end
  resource :my_listings, only: :show
  resource :saved_listings, only: :show
  resource :search, only: :show, controller: "feed/searches" do
    get "tags/:tag", to: "feed/searches/tags#show", as: "tags"
  end

  resources :conversations, only: [ :index, :show ] do
    resources :messages, only: [ :create ]
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  include AccessPolicy
  belongs_to :listing
  belongs_to :seller, class_name: "Organization"
  belongs_to :buyer, class_name: "Organization"

  has_many :messages, dependent: :destroy

  scope :current_organization, -> {
    where(seller: Current.organization)
    .or(where(buyer: Current.organization))
  }

  scope :for_display, -> {
    joins(:messages)
    .includes(:seller, :listing)
    .order(created_at: :desc)
    .distinct
  }

  before_validation :set_seller, unless: :persisted?

  private

  def set_seller
    self.seller = listing.organization
  end
end

app/models/conversation/access_policy.rb
module Conversation::AccessPolicy
  def show?(_user = nil)
    Current.organization == seller || Current.organization == buyer
  end

  def can_message?(_user = nil)
    show?
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  skip_authorization only: :index

  def index
    @conversations = Conversation.current_organization.for_display
  end

  def show
    authorize! @conversation.show?(current_user)
    @message = @conversation.messages.build
  end

  private

  def authorizable_resource
    @conversation = Conversation.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= link_to conversation_path(conversation), class: "m-2", data: { turbo_frame: :conversation } do %>
    <%= tag.div class: class_names(
        "box",
        { "has-background-info-dark has-text-white":
          conversation.seller == Current.organization}
    ),
    id: dom_id(conversation) do %>
        <h4 class="is-size-4">
            <%= conversation.listing.title %>
        </h4>
        <p class="has-text-right">
            <%= local_date(conversation.created_at) %>
        </p>
    <% end %>
<% end %>

app/views/conversations/index.html+mobile.erb
<layout-columns class="columns">
    <layout-column class="column p-4" id="conversations">
        <%= render(@conversations) || tag.h2(class: "has-text-centered is-size-3") do%>
            <%= t(".no_conversations")%>
        <%end%>
    </layout-column>
</layout-columns>

app/views/conversations/index.html.erb
<layout-columns class="columns">
    <layout-column id="conversations" class="column is-one-quarter p-4">
        <%= render(@conversations) || tag.h2(class: "has-text-centered is-size-3") do %>
            <%= t(".no_conversations") %>
        <% end %>
    </layout-column>

    <%= turbo_frame_tag :conversation, class: "column is-three-quarters" do %>
        <br><br><br>
        <h2 class="has-text-centered is-size-2">
            <%= t(".no_selected_conversation")%>
        </h2>
    <% end %>
</layout-columns>

app/views/conversations/show.html.erb
<%= turbo_frame_tag :conversation do %>
    <div class="p-3">
        <%= render "messages/messages", conversation: @conversation %>
    </div>

    <%= form_with(
        model: @message,
        url: conversation_messages_path(@conversation),
        class: "p-4"
    ) do |f| %>
        <form-field class="field">
            <%= f.text_area :body, class: "textarea has-fixed-size"%>
        </form-field>

        <layout-group class="buttons is-right mt-4">
            <%= f.submit t(".send"), class: "button is-primary" %>
        </layout-group>
    <% end %>

    <%= turbo_stream.switch_class(dom_id(@conversation), "is-active") %>
<% end %>