config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  root "feed#show"

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :listings, except: :index do
    scope module: :listings do
      post :draft, to: "drafts#create", on: :collection
      patch :draft, to: "drafts#update"

      resource :contact, only: [ :show ], controller: "contact"
    end

    resource :saved_listings, only: [ :create, :destroy ], path: "save"
  end
  resource :my_listings, only: :show
  resource :saved_listings, only: :show
  resource :search, only: :show, controller: "feed/searches" do
    get "tags/:tag", to: "feed/searches/tags#show", as: "tags"
  end

  resources :conversations, only: [ :index, :show ] do
    resources :messages, only: [ :create ]
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/address.rb
class Address < ApplicationRecord
    include PermittedAttributes

    belongs_to :addressable, polymorphic: true

    validates :line_1, :line_2, :city, :country, :postcode, presence: true
    attribute :country, default: "KE"

    geocoded_by :redacted
    after_validation :geocode

    def redacted
        "#{city}, #{postcode}"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  include HumanEnum
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  include AccessPolicy
  belongs_to :listing
  belongs_to :seller, class_name: "Organization"
  belongs_to :buyer, class_name: "Organization"

  has_many :messages, dependent: :destroy

  scope :current_organization, -> {
    where(seller: Current.organization)
    .or(where(buyer: Current.organization))
  }

  scope :for_display, -> {
    joins(:messages)
    .includes(:seller, :listing)
    .order(created_at: :desc)
    .distinct
  }

  before_validation :set_seller, unless: :persisted?

  private

  def set_seller
    self.seller = listing.organization
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user, :organization
end

app/models/listing.rb
class Listing < ApplicationRecord
    include HasAddress, PermittedAttributes, AccessPolicy,
    Publishable, Expireable, Searchable

    belongs_to :creator, class_name: "User"
    belongs_to :organization

    has_one_attached :cover_photo
    has_rich_text :description
    has_many :conversations

    enum :condition, {
        mint: "mint",
        near_mint: "near_mint",
        used: "used",
        defective: "defective"
    }

    enum :status, {
        draft: "draft", published: "published",
        expired: "expired"
    }

    validates :title, length: { in: 10..100 }
    validates :price, numericality: { only_integer: true }
    validates :condition, presence: true
    validates :tags, length: { in: 1..5 }
    validates :cover_photo, presence: true
    validates :description, presence: true

    before_save :downcase_tags

    scope :feed, -> {
        published
        .order(created_at: :desc)
        .includes(:address)
        .with_attached_cover_photo
    }

    def saved_by?(user)
        return false unless user.present?

        user.saved_listings.exists?(id: id)
    end

    def expiry_date
        published_on.end_of_day + 30.days
    end

    private

    def downcase_tags
        self.tags = tags.map(&:downcase)
    end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :from, class_name: "Organization"
  belongs_to :sender, class_name: "User", optional: true

  validates :body, presence: true

  scope :for_display, -> {
    includes(:from, :sender)
    .where.not(created_at: nil)
    .order(created_at: :asc)
  }
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :memberships, dependent: :destroy
    has_many :members, through: :memberships, source: :user
    has_many :listings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  has_and_belongs_to_many :saved_listings, join_table: "saved_listings", class_name: "Listing"

  before_validation :remove_extra_whitespace

  private

  def remove_extra_whitespace
    self.name = self.name&.strip
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    layout "error"

    def show
        @exception = request.env["action_dispatch.exception"]
        @status_code = @exception.try(:status_code) ||
                        ActionDispatch::ExceptionWrapper.new(
                            request.env, @exception
                        ).status_code

        render view_for_code(@status_code), status: @status_code
    end

    private

    def view_for_code(code)
        supported_error_codes.fetch(code, "404")
    end

    def supported_error_codes
        {
            403 => "403",
            404 => "404",
            500 => "500"
        }
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def show
    @search = Listings::Search.new
    @pagy, @listings = pagy(Listing.feed)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  skip_authorization only: [ :new, :create ]

  drop_breadcrumb -> { @listing&.title },
                  -> { listing_path(@listing) },
                  except: [ :new, :create ]

  def show
  end

  def new
    @listing = Listing.new
    @listing.build_address

    drop_breadcrumb t("listings.breadcrumbs.new")
  end

  def create
    drop_breadcrumb t("listings.breadcrumbs.new")

    @listing = Listing.new(
      listing_params.with_defaults(
        creator: current_user,
        organization: Current.organization,
        status: :published
      )
    )

    if @listing.save
      redirect_to listing_path(@listing), flash: { success: t(".success") }, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    drop_breadcrumb t("listings.breadcrumbs.edit")
  end

  def update
    drop_breadcrumb t("listings.breadcrumbs.edit")

    @listing.assign_attributes(
      listing_params.with_defaults(
        status: :published
      )
    )

    if @listing.save
      flash[:success] = t(".success")
      recede_or_redirect_to listing_path(@listing),
        status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
    flash[:success] = t(".success")
    redirect_to my_listings_path, status: :see_other
  end

  private

  def listing_params
    params.fetch(:listing, {}).permit(
      Listing.permitted_attributes
    )
  end

  def authorizable_resource
    @listing = Listing.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend

  def show_paginator?(pagy)
    pagy.present? && pagy.pages > 1
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
  def listing_status_tag_classes(listing)
    classes = [ "tag" ]

    classes << "is-danger" if listing.expired?

    classes.join(" ")
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/my_listings_helper.rb
module MyListingsHelper
end

app/helpers/saved_listings_helper.rb
module SavedListingsHelper
end

app/helpers/svg_helper.rb
module SvgHelper
  def svg(svg_name, **attributes)
    svg_markup = render file: "#{Rails.root}/app/views/shared/svg/#{svg_name}.svg"

    xml = Nokogiri::XML(svg_markup)
    attributes&.each do |key, value|
      xml.root.set_attribute(key.to_s, value)
    end

    xml.root.to_xml.html_safe
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/pagy/_nav.html.erb
<%# 
  This template is i18n-ready: if you don't use i18n, 
  you can replace the pagy_t calls with actual strings like 
  ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;"). 
  The link variable is set to a proc that returns the link tag.
  Usage: link.call(page_number [, text [, extra_attributes_string]])
-%>

<% link = pagy_link_proc(pagy) %>

<nav class="pagy-bulma-nav pagination is-centered" role="navigation" aria-label="pagination">

  <%# Previous button %>
  <% if pagy.prev %>
    <%== link.call(
      pagy.prev,
      pagy_t('pagy.nav.prev'),
      'class="pagination-previous" aria-label="previous page"'
    ) %>
  <% else %>
    <a class="pagination-previous" disabled>
      <%== pagy_t('pagy.nav.prev') %>
    </a>
  <% end %>

  <%# Next button %>
  <% if pagy.next %>
    <%== link.call(
      pagy.next,
      pagy_t('pagy.nav.next'),
      'class="pagination-next" aria-label="next page"'
    ) %>
  <% else %>
    <a class="pagination-next" disabled>
      <%== pagy_t('pagy.nav.next') %>
    </a>
  <% end %>

  <%# Page links %>
  <ul class="pagination-list">
    <% pagy.series.each do |item| %>
      <% if item.is_a?(Integer) %>
        <li>
          <%== link.call(
            item,
            item,
            %(class="pagination-link" aria-label="goto page #{item}")
          ) %>
        </li>
      <% elsif item.is_a?(String) %>
        <li>
          <%== link.call(
            item,
            item,
            %(class="pagination-link is-current" aria-label="page #{item}" aria-current="page")
          ) %>
        </li>
      <% elsif item == :gap %>
        <li>
          <span class="pagination-ellipsis">
            <%== pagy_t('pagy.nav.gap') %>
          </span>
        </li>
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/shared/_breadcrumbs.html.erb
<nav class="breadcrumb is-centered mt-6">
    <ul>
        <li>
            <%= link_to root_path do %>
                <%= svg "home", class: "icon" %>
            <% end %>
        </li>

        <% breadcrumbs.tail.each do |crumb| %>
            <li>
                <%= link_to crumb.label, crumb.path %>
            </li>
        <% end %>

        <li class="is-active">
            <%= link_to breadcrumbs.head.label, breadcrumbs.head.path %>
        </li>
    </ul>
</nav>

app/views/shared/_flashes.html.erb
<div class="container is-fluid" data-turbo-cache="false">
    <% flash.each do |level, msg| %>
        <%= tag.div class: "notification is-#{level} is-light has-text-centered mt-4" do %>
            <%= msg %>
        <% end %>
    <% end %>
</div>

app/views/shared/_image_field.html.erb
<%= tag.image_upload_field(
    data: {
        controller: "image-upload",
        image_upload_blob_url_template_value: rails_service_blob_url(
            ":signed_id", ":filename"
        )
    }
) do %>
    <div class="file is-large is-boxed is-centered">
        <label class="file-label" data-image-upload-target="cta">
            <%= form.file_field(
                nil,
                id: nil,
                class: "file-input",
                accept: "image/*",
                direct_upload: true,
                required: true,
                data: {
                    action: "image-upload#upload",
                    image_upload_target: "fileInput"
                }
            )%>
            <%= form.hidden_field(
                attribute,
                value: form.object.cover_photo&.signed_id,
                data: {
                    image_upload_target: "hiddenInput"
                }
            )%>
            <span class="file-cta">
                <%= svg "upload", class: "file-icon" %>
                <span class="file-label">
                    <%= label %>
                </span>
            </span>
        </label>
    </div>

    <figure class="image is-relative">
        <% url =
            form.object.cover_photo.present? ?
            url_for(form.object.cover_photo) : ""
        %>
        <%= image_tag url, data: { image_upload_target: "preview" } %>
    </figure>

    <progress
        value="0"
        max="100"
        class="progress is-primary"
        data-image-upload-target="progress"
    ></progress>

    <%= tag.div(
        class: "buttons is-centered is-hidden mt-3",
        data: {
            image_upload_target: "remove"
        }
    ) do %>
        <%= tag.button(
            class: "button is-danger",
            type: "button",
            data: {
                action: "image-upload#remove"
            }
        ) do %>
            <%= t(".remove_image") %>
        <%end %>
    <% end %>
<% end %>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag :modal do %>
    <div class="modal is-active" data-controller="modal">
        <div class="modal-background"></div>
        <%= yield %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-link" data-controller="navbar">
    <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
            <strong class="is-size-3">Snap</strong>
        <% end %>

        <a role="button" class="navbar-burger" data-navbar-target="burger" aria-label="menu" aria-expanded="false" data-action="click->navbar#toggle">
            <span></span>
            <span></span>
            <span></span>
        </a>
    </div>

    <navbar-menu class="navbar-menu" data-navbar-target="menu">
        <div class="navbar-start">
            <%= link_to t(".create_ad"), new_listing_path, class: "navbar-item" %>
            <%= link_to t(".messages"), conversations_path, class: "navbar-item" if user_signed_in? %>
        </div>

        <div class="navbar-end">
            <%= tag.div class: "navbar-item has-dropdown is-hoverable mr-4" do %>
                <%= link_to current_user.name, "#", class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                    <%= link_to t(".profile"), edit_user_registration_path, class: "navbar-item" %>
                    <%= link_to t(".my_ads"), my_listings_path, class: "navbar-item" %>
                    <%= link_to t(".saved_ads"), saved_listings_path, class: "navbar-item" %>
                    
                    <hr class="navbar-divider">

                    <%= link_to t(".logout"), destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-item" %>
                </div>
            <% end if user_signed_in? %>

            <%= tag.div class: "navbar-item" do %>
                <div class="buttons">
                    <%= link_to t(".sign_up"), new_user_registration_path, class: "button is-primary" %>
                    <%= link_to t(".login"), new_user_session_path, class: "button is-light" %>
                </div>
            <% end unless user_signed_in?%>
        </div>
    </navbar-menu>
</nav>